fix(database): Add $ref to observables (#447)
* feat(FirebaseObjectObservable, FirebaseArrayObservable): Add $ref to observables

Makes the firebase.database.Reference used to create the observable public so that it can be used for accessing child records and paths relative to this collection/object.

This closes #294

* Locked zone.js to 0.6.12 per bug angular/zone.js#404, bug #468 created to address this.
Commented test units to correct `error TS2339`; bug #467 created to address this.